on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  label-as-new:
    runs-on: ubuntu-latest

    steps:
      - name: Label as "new"
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90 # 1.0.4
        with:
          add-labels: "new"
          ignore-if-assigned: false
          ignore-if-labeled: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
